services:
  serverhud-server:
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    command: bash -c "/usr/local/bin/serverhud_docker.sh"
    image: jchase23/serverhud-server
    volumes:
      - serverhud:/home/serverhud
volumes:
  serverhud:   # Defining the serverhud volume